
sudo: false
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "5"
  - "4"
  - "0.10"
before_install:
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
#  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10",
    - node_js: "5",
    - node_js: "4"
